"""empty message

Revision ID: 323ece76996e
Revises: None
Create Date: 2015-05-01 11:15:10.898163

"""

# revision identifiers, used by Alembic.
revision = '323ece76996e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
