"""empty message

Revision ID: 67b02d32973
Revises: 3f98032416b9
Create Date: 2015-05-02 16:58:12.954470

"""

# revision identifiers, used by Alembic.
revision = '67b02d32973'
down_revision = '3f98032416b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    ### end Alembic commands ###
